version: "3.5"

services:
  exekube:
    build: ./.docker
    working_dir: /exekube
    environment:
      GOOGLE_CREDENTIALS: /exekube/credentials.json
      TF_LOG:
      TF_INPUT: 0
      XK_LIVE_DIR:

      TF_VAR_gcp_project:
      TF_VAR_gcp_remote_state_bucket:

      TF_VAR_cloudflare:
      TF_VAR_cluster_dns_zones:
      TF_VAR_chartmuseum:
      TF_VAR_jenkins:
      TF_VAR_docker_registry:
      TF_VAR_rails_app:
    ports:
      - 8001:8001
    volumes:
      - .:/exekube
      - ./config/helm:/root/.helm
      - ./config/terragrunt:/root/.terragrunt
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
