version: "3"

services:
  # Build Exekube images and tag them
  # Usage: `docker-compose build <service-name>`
  google:
    image: exekube/exekube:0.5.0-google
    build:
      context: .
      dockerfile: dockerfiles/google/Dockerfile
  aws:
    image: exekube/exekube:0.4.0-aws
    build:
      context: .
      dockerfile: dockerfiles/aws/Dockerfile
  alicloud:
    image: exekube/exekube:0.4.0-alicloud
    build:
      context: .
      dockerfile: dockerfiles/alicloud/Dockerfile

  # Start local mkdocs server for writing Exekube documentation
  # Usage: `docker-compose up docs`
  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - .:/docs
    ports:
      - 8000:8000
    entrypoint: mkdocs
    command:
      - serve
      - --livereload
      - --dev-addr=0.0.0.0:8000
