apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nginx-react.fullname" . }}
  labels:
    app: {{ template "nginx-react.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "nginx-react.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec: # PodSpec
      volumes:
        - name: {{ template "nginx-react.fullname" . }}-conf
          configMap:
            name: {{ template "nginx-react.fullname" . }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.servicePort | int }}
          volumeMounts:
            - name: {{ template "nginx-react.fullname" . }}-conf
              mountPath: /etc/nginx/conf.d
          resources:
{{ toYaml .Values.resources | indent 12 }}
