concourse:
  externalURL: https://${domain_name}
  githubAuth:
    enabled: true
    user: ilyasotkov

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
    hosts:
      - ${domain_name}
    tls:
      - secretName: ${domain_name}-tls
        hosts:
          - ${domain_name}

postgresql:
  postgresDatabase: concourse

rbac:
  create: true

credentialManager:
  kubernetes:
    enabled: true
    namespacePrefix: "concourse-"
    teams:
      - main

  vault:
    enabled: false
    # enabled: true
    # url: https://vault-vault:8200
    # pathPrefix: "/concourse"
    # authBackend: ""
    # caCert: true

secrets:
  create: false
